name: Check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt
      env:
        GFE_PASSWORD: ${{ secrets.GFE_PASSWORD }}
      run: ./gradlew decryptFiles
    - name: Check
      run: ./gradlew check
